# Generated by Django 4.2.28 on 2026-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('BASIC', 'Basic - Free'), ('STANDARD', 'Standard - $14.99/month'), ('PRO', 'Pro - $19.99/month')], default='BASIC', max_length=10),
        ),
    ]
