# Generated by Django 4.2.28 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemai', '0003_alter_movie_options_movie_backdrop_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streaming_providers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('BASIC', 'Basic - Free'), ('STANDARD', 'Standard - £9.99/month'), ('PRO', 'Pro - £14.99/month')], default='BASIC', max_length=10),
        ),
    ]
