# Generated by Django 4.2.28 on 2026-02-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemai', '0004_movie_streaming_providers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('BASIC', 'Basic - Free'), ('STANDARD', 'Standard - £9.99/month')], default='BASIC', max_length=10),
        ),
    ]
